version: "3"
services:
    front:
        build: 
            context: ./
            dockerfile: Dockerfile.development
        volumes:
            - ./:/app
            #- '/app/node_modules'
        ports:
            - "8080:8080"
        tty: true
        container_name: "front_projetin"
        
